version: 2.1

orbs:
  sixrs-gke: sixriversystems/sixrs-gke@7

aliases:
  - &node_image cimg/node:16.20.1

jobs:
  build:
    docker:
      - image: *node_image
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: lint
          command: 'npm run lint'
      - sixrs-gke/run-release
      - persist_to_workspace:
          root: ./
          paths:
            - .

  publish:
    docker:
      - image: *node_image
    steps:
      - attach_workspace:
          at: ./
      - sixrs-gke/npm-public-publish:
          params: '--tag latest'

  publish-feature:
    docker:
      - image: *node_image
    steps:
      - attach_workspace:
          at: ./
      - sixrs-gke/npm-public-publish:
          params: '--tag feature'

workflows:
  build:
    jobs:
      - build:
          context: 6rs-circle
      - publish:
          context: 6rs-public-npm
          requires:
            - build
          filters:
            branches:
              only:
                - main
      - publish-feature:
          context: 6rs-public-npm
          requires:
            - build
          filters:
            branches:
              only:
                - '/^feat/.*/'
