version: 2.1
orbs:
  sixrs-gke: sixriversystems/sixrs-gke@7
aliases:
  - &node_image cimg/node:14.20.1
jobs:
  build:
    docker:
      - image: *node_image
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: lint
          command: 'npm run lint'
      - persist_to_workspace:
          root: ./
          paths:
            - .
  publish:
    docker:
      - image: *node_image
    steps:
      - attach_workspace:
          at: ./
      - sixrs-gke/run-release
      - sixrs-gke/npm-public-publish
workflows:
  version: 2
  build:
    jobs:
      - build
      - publish:
          context: 6rs-public-npm
          requires:
            - build
          filters:
            branches:
              only:
                - main
