name: auto approve
on: pull_request

jobs:
  approve-dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-approve Dependabot pull requests
        if: ${{ github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' }}
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.SRS_MACHINE_GITHUB_TOKEN }}
