# https://github.blog/2021-03-11-scripting-with-github-cli/#using-gh-in-github-actions
name: Auto-merge

on:
  pull_request:
    types: [opened]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge for new PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
